### ISSUE TITLE
Sometimes when click on the view it does not show the cursor

### ISSUE THREAD

**Issue by jrcacd** [HITGIF/TextFieldBoxes#14]

**Comment by HITGIF** [comment]
**fixed in release 1.2.1**

**Comment by jrcacd** [comment]
Very good

**Comment by pess0a** [comment]
happen to me, at first clik it doesnt show the cursor, after click for edit some wrong letter the cursor appears.

**Comment by HITGIF** [comment]
@pess0a fixed again in **release 1.3.6**

**Comment by ramden** [comment]
@HITGIF This still occurs on 1.4.5. 
After clicking on the clear button there is no cursor blinking.

Also after clicking on another field and entering the original again (that was cleared before) there is no cursor blinking, only after entering text. 

Is this the desired behavior or a bug?

If its desired ... is there a way to make the field always blink when it is focused?
